#!/usr/bin/env bash
set -x
BBSIM=$(kubectl get --all-namespaces -l app=bbsim svc -o json | jq -r '.items[] | .metadata.name + "." + .metadata.namespace + ".svc:50060"' | head -1)
exec voltctl device enable "$(voltctl device create -t openolt -H "$BBSIM")"
